### ISSUE TITLE
Zoom In/Out/Reset commands

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/SynEdit#102]
These commands increase/decrease/reset the font size of the editor and the gutter.

Three new commands to be implement.

- ecZoomIn (Alt+Num +)
- ecZoomOut (Alt+Num -)
- ecZoomReset (Alt+Num 0)

Ctrl+MouseWheel Up/Down also acts as Zoom In/Out

MouseWheel operations
- Ctrl+MouseWheel Up/Down -> Zoom In/Out
- MouseWheel Up/Down -> Scroll vertically
- Ctrl +Shift+MouseWheel Up/Down -> Scroll vertically by half page
- Shift + MouseWheel Up/Down -> Scroll horizontally 
- MouseWheel Left/Right -> Scroll horizontally 
- Ctrl+Shift+MouseWheel Left/Right -> Scroll horizontally by half page

**Comment by pyscripter** [comment]
@MShark67 What do you think?

**Comment by MShark67** [comment]
Looks very nice!

**Comment by pyscripter** [comment]
@MShark67 One thing that does not work with scroll is tilting the mouse wheel.  It appears to have no impact.
When I do the same in MS Edge, I see a floating scroll button and when I move it the direction of the mouse move.
VS Code and other apps also fail to respond to tilting the mouse wheel, but Delphi editor does work similarly (see image)!

![image](https://github.com/user-attachments/assets/0af12d5d-391d-483d-be62-c18388903f50)

***Update:***
Actually this is activated by receiving the message WM_MBUTTONDOWN which is translated to 

`  DoMouseDown(Message, mbMiddle, []);
`

It may be worth emulating the same behavior. VirtualTreeView does that and may serve as a guide. It calls it wheel panning:
- https://github.com/JAM-Software/Virtual-TreeView/blob/master/Source/VirtualTrees.BaseTree.pas#L7461
- https://github.com/JAM-Software/Virtual-TreeView/blob/master/Source/VirtualTrees.BaseTree.pas#L14847

Note:  My mouse has a separate wheel for horizontal scrolling, so tilting the vertical wheel is the same as clicking it.  Confirmed horizontal scrolling with tilting works using a different mouse.

**Comment by MShark67** [comment]
It seems to be rare to find a mouse nowadays with a left/right tilting mousewheel, but I actually have one that I use on my laptop and SynEdit does work with it (as I used it for testing/debugging that feature.)  Btw: It's the original version of the Microsoft Sculpt Bluetooth with 4-way scroll wheel (they still appear to make it, but it looks different from mine.)  The Shift-Mousewheel up/down horizontal scrolling was added for mice without that ability.   I can certainly look into adding the mouse panning feature though I'm swamped right now and won't get a change to look at it for a few weeks at least.

**Comment by pyscripter** [comment]
> . I can certainly look into adding the mouse panning feature though I'm swamped right now and won't get a change to look at it for a few weeks at least.

Nevermind.  I have done some work looking at how VTV does it and contributed some code,  See https://github.com/JAM-Software/Virtual-TreeView/issues/1270.

**Comment by MShark67** [comment]
I'd like to update a font info display when the SynEdit's font changes.  Is there a current way to do this?  If not, would adding scFontChanged to TSynStatusChange be a good way?  Thanks!

**Comment by pyscripter** [comment]
> I'd like to update a font info display when the SynEdit's font changes. Is there a current way to do this? If not, would adding scFontChanged to TSynStatusChange be a good way? Thanks!

Presumably, your application has code, which allows the user to change font.  Why don't update the font info display at that point?

You can also do:

```pascal
OldFontOnChange := SynEdit.Font.OnChange;
SynEdit.Font.Change := NewFontOnChange;
```

And in NewFontOnChange, call first the OldFontOnChange and then do whatever you want.

**Comment by MShark67** [comment]
This is really directly related to the zoom feature.  I wanted to update the font size when it's changed, and that's internal to the control, hence an event.  I can certainly hook font.onchange, but it may not be a terrible idea to have a status change for it.  No worries if not.

**Comment by pyscripter** [comment]
I see!  I was wondering why you posted it here.  I should have guessed...

Let me think about it.

**Comment by MShark67** [comment]
I just wanted to mention that hooking Font.OnChange works just fine.  It is important to know to re-hook it at the end of the handler as SynFontChanged nils the handler and then sets it back to itself to avoid recursion.

**Comment by pyscripter** [comment]
I think the following should work:

- you store the old handler 
- assign your handler to Font.OnChange

Your handler
- calls first the old one 
- then does whatever you want.
- finally it assigns your handler to Font.OnChange

**Comment by MShark67** [comment]
Sorry, that's exactly what I was trying to convey above.  I must admit that I don't like to use event chaining if I can help it.  It seems brittle.   It does work in this case and so no worries, but I'd vote for a status message on internal font changes (or zoom level if you feel that's better.)   Something like adding scFont or scZoom to TSynStatusChange might be a good solution.  This is certainly a minor issue.

**Comment by pyscripter** [comment]
Understood.  Could you please open a new issue for this?

**Comment by dados** [comment]
Hi,

The zoom feature is nice but this is hardcoded with ctrl+mousewheel = Font/Zoom. 
Before we had ctr+mousewheel = page scroll like in Delphi IDE.

I had already integrated ctr+shift+mousewheel = Font/Zoom
Could you please think about adding an option to disable/enable this zoom function with the mousewheel or maybe an option for a combination + mousewheel.

```
procedure TSynEditScrollBars.DoMouseWheel(Shift: TShiftState;  WheelDelta: Integer; MousePos: TPoint);
var
  WheelClicks: Integer;
  LinesToScroll: Integer;
  CharsToScroll: Integer;
begin
  if [ssCtrl, ssAlt, ssShift, ssHorizontal] * Shift = [ssCtrl] then
  begin
    FMouseWheelVertAccumulator := 0;
    FOwner.Zoom(Sign(WheelDelta));   <---
  end
```

Thanks :)

**Comment by pyscripter** [comment]
@dados 
- Using Ctrl + MouseWheel is the common way to Zoom in and out (Edge, Excel, Word etc.)   It is what most users have come to expect.
- Also the use of Shft+MouseWheel is commonly used for horizontal scrolling, (Edge, VS Code etc.)
- The use of Ctrl + MouseWheel for (half) page scrolling is quite specific to the Delphi IDE
- You can still do page scrolling by Shft+Ctrl+MouseWheel. 
- I understand that if you had an application with a different functioning of the Mouse Wheel,  it is annoying to have to change what users are accustomed to.  However, I am reluctant to add more options for this.   

But please note that the first thing that DoMouseWheel does is to call the OnMouseWheel event.   If you handle that event and set Result to True no further processing of the event will take place by SynEdit.  I thinks this is the easiest way to maintain the current functioning of your code.

Also DoMouseWheel is virtual.  So you can always overwrite it in a descendent (or an interposer) class.  In a couple of lines you can call the inherited method with changed shift. eg.
```pascal
if Shift = [ssCtrl] then 
begin
  var NewShift  := Shift + [ssShift];
  inherited DoMouseWheel(NewShift, WheelDelta, MousePos)
end
else
  inherited;
```

**Comment by dados** [comment]
Okey, thanks :)
