### ISSUE TITLE
Delphi 10.3 Rio

### ISSUE THREAD

**Issue by JEH-HPRO** [pyscripter/SynEdit#107]
Hi

I don´t know if I am missing something but I have downloaded the ZIP file and try to install package according my Delphi version (10.3 Rio). First I received some errors and change Screen.DefaultPixelPerInch to Screen.PixelPerInch in many places. I have changed and/or comment just two lines to avoid the errors:

unit SynCompletionProposal;
In the procedure procedure TSynBaseCompletionProposalForm.PaintGripper;

      details := StyleServices(Self).GetElementDetails(tsGripper);        <----- 

unit SynAccessibility
function TSynTextRangeProvider.GetBoundingRectangles(out RetVal: PSafeArray): HResult;

      R := FSynEdit.ClientToScreen(R);   <-----

So far so good. My apps compile and run OK without any warning. But I can´t drop another TSynEdit component neither create a new one using code. They both complains abour "there are no parent" message.

Am I missing something ?
Thanks in advance
Eduardo

**Comment by pyscripter** [comment]
Could you please 
- download zip again
- Install again
- Then test

Is tsGripper not defined in Delphi Rio?

Also I wonder why you had to comment out the following:
  R := FSynEdit.ClientToScreen(R);   <-----

**Comment by JEH-HPRO** [comment]
Hi

Thanks for the feedback.

I have downloaded again and repeated the operation.

The lines I changed also have changed again but the problem has gone.

The line below was comment out because R is declared as TRect and should be TPoint.
R := FSynEdit.ClientToScreen(R);

Another change I have made was in unit SynCompletionProposal

Line 1595 I have changed for because the compiler complains about original line:
details := LStyle.GetElementDetails(tsGripper);

Eduardo

________________________________
De: pyscripter ***@***.***>
Enviado: quarta-feira, 13 de novembro de 2024 18:44
Para: pyscripter/SynEdit ***@***.***>
Cc: Eduardo Helminsky | HPro Soluções de TI ***@***.***>; Author ***@***.***>
Assunto: Re: [pyscripter/SynEdit] Delphi 10.3 Rio (Issue #107)


Could you please

  *   download zip again
  *   Install again
  *   Then test

Is tsGripper not defined in Delphi Rio?

Also I wonder why you had to comment out the following:
R := FSynEdit.ClientToScreen(R); <-----
