### ISSUE TITLE
Home key toggling with eoEnhanceHomeKey.

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#108]
Currently the home key doesn't toggle between the first character on a line and the first non-whiltespace character on a line.  I think the fix is just a minor change in DoHomeKey:

```
    if (NewPos.Column > FirstNonBlank) or (NewPos.Column = 1) then
      NewPos.Column := FirstNonBlank
    else
      NewPos.Column := 1;
```

**Comment by pyscripter** [comment]
It seems to work OK here.  Could  you please show an example where it is not working?

**Comment by MShark67** [comment]
No problem.  In VSCode (and other editors) continuing to press home will toggle between character position 1 and the first non-ws character.  Currently SynEdit just stops at position 1 and does not "toggle."

So to reproduce the issue:
Make sure eoEnhanceHomeKey is on.  Type some whitespace and then a word.  Press Home and it moves to the first non-ws character.  Press home again and it goes to position 1.  Press home again and it stays in position 1, but (if we want to match VSCode) should toggle back to the first non-ws character.

**Comment by pyscripter** [comment]
> In VSCode (and other editors) continuing to press home will toggle between character position 1 and the first non-ws character. Currently SynEdit just stops at position 1 and does not "toggle."

Aha! Delphi does the same.

**Comment by pyscripter** [comment]
Done!  The End key appears to toggle between the two positions....

**Comment by pyscripter** [comment]
@MShark67 
I noticed there is a difference between Delphi and VS Code.

If the cursor is  between before the first character but after column 1,  pressing home in VS Code takes you to the first char while in Delphi it takes you to column 1.  Visual Studio also works like VS Code.
Which one should we adopt?  The code now works like Delphi.

**Comment by pyscripter** [comment]
Changed the code to match VS Code.  It also matches the way the enhanced END key works.

**Comment by MShark67** [comment]
Nice work.  I actually prefer the Delphi one (moving to pos 1 first, then first non-ws, but I think that's just up to whatever someone is used to.  By the way, the ability to make a selection, use Alt-End to caret the ends, then press the home key, and then do shift-Home to select all leading whitespace and replace it, is fantastic.

**Comment by pyscripter** [comment]
Nice indeed.  Multiple cursors can be quite useful.

By the way one change that may have been unnoticed, is that code folding has been optimized and should be much faster on very large documents.
