### ISSUE TITLE
Per Monitor DPI awareness

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/SynEdit#11]
Currently SynEdit can be used in System DPI aware applications.  Using features introduced in Delphi Rio, it should be relatively straightforward to make the component per Monitor DPI aware.

**Comment by softbug123** [comment]
can Synedit used on FMX?

**Comment by pyscripter** [comment]
I am afraid not.

**Comment by pyscripter** [comment]
Fixed at https://github.com/TurboPack/SynEdit.
