### ISSUE TITLE
Possible issue with SelAvail when adding carets after a selection.

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#111]
I'm not sure if this is a bug, but SelAvail seems to only depend on the state of the last caret created.  This seems incorrect if you have an existing selection or selections and then add a caret with Alt-Click (with no drag.)
 
The steps to reproduce this are:

Load some text into SynEdit.
Make a single selection of any kind. SelAvail will be true.
Now Alt-Click anywhere else to add a caret.
Notice that even though the first Caret is at the end of a selection, that SelAvail returns false.

Note that this causes no issues at all in the handling of the carets, typing something replaces the selections just as you'd expect. It just semed that SelAvail should be true if there are any selections at all (or perhaps I'm missing something!)

Thanks, as always!

-Mark

**Comment by pyscripter** [comment]
To maintain compatibility with earlier versions, SelText, SelStart, CaretXY, BlockBegin etc. all refer to the active selection.  For consistency SelAvail also refers to the active selection.

To check whether any of the many selections contains text use Selections.IsEmpty.  More generally, to work with multiple cursors you need to use the Selections object.  

This is explained in https://github.com/pyscripter/SynEdit/blob/master/Doc/Multi-caret.md
