### ISSUE TITLE
Mouse selection with scroll 

### ISSUE THREAD

**Issue by JEH-HPRO** [pyscripter/SynEdit#112]
Hi

If I select the text with mouse it works ok.

But if the selection force the window to scroll down then always the selection ends in the wrong position.

Steps to reproduce:
1) Open a file with 200 lines or more
2) Go to last line in the view, click and scroll down a few lines
3) Release the mouse button and click in any line above in the text starting a new selection (here the problem happen).

I am using Delphi 10.3

**Comment by pyscripter** [comment]
Thanks for reporting it.
That was a silly error in the previous commit.   Could you please try again and confirm the problem is solved?

**Comment by JEH-HPRO** [comment]
Hi

Yep, the error has gone. Thank you very much for a prompt support and resolution.

Regards
Eduardo

________________________________
De: pyscripter ***@***.***>
Enviado: quarta-feira, 11 de dezembro de 2024 20:19
Para: pyscripter/SynEdit ***@***.***>
Cc: Eduardo Helminsky | HPro Soluções de TI ***@***.***>; Author ***@***.***>
Assunto: Re: [pyscripter/SynEdit] Mouse selection with scroll (Issue #112)


Thanks for reporting it.
That was a silly error in the previous commit. Could you please try again and confirm the problem is solved?
