### ISSUE TITLE
Allow creating additional multi-caret selections using current non-word selection with Ctrl-W. 

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#114]
Ctrl + W would work as follows:

No selection: Select Word

Selection: Add multi-caret selection of the next match whether the selection is a word or not.

This would match VSCode's Ctrl-D behavior.

**Comment by pyscripter** [comment]
@MShark67 Could you please test the changes?

**Comment by MShark67** [comment]
I can't find anything wrong with it.  Great job!
