### ISSUE TITLE
Synedit-2 fails to install using MultiInstaller

### ISSUE THREAD

**Issue by raelb** [pyscripter/SynEdit#12]
Hi
I was running the pyscripter MultiInstaller in Thirdparty folder. It fails to install SynEdit-2.

Error: It is missing unit SynMemo

Fix: Need to add unit SynMemo from other distribution, or remove part to install TSynMemo from SynEditReg.pas

  RegisterComponents(SYNS_ComponentsPage, [TSynEdit, TSynMemo]);

**Comment by pyscripter** [comment]
SynMemo was removed from the project but had forgot to remove it from the registration unit.  Fixed now.
