### ISSUE TITLE
Range check violation with eoShowSpecialChars and tabs in PaintToken

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#13]
The following code generates a range check violation when tabwidth is 2 and text is a tab delimited grid of numbers and eoShowSpecialChars is included.

    for i := 0 to TabLen - 1 do           //wipe the text out so we don't
      sTabbedToken[TabStart + i] := #32;  //count it again

My quick fix was to add a length check:

    for i := 0 to TabLen - 1 do           //wipe the text out so we don't
      if ((TabStart + i) <= Length(sTabbedToken)) then    // changed
        sTabbedToken[TabStart + i] := #32;  //count it again

**Comment by pyscripter** [comment]
Sorry about the delay in responding to this.   I am looking into this bug and I could reproducing only when **selecting** hard tabs with **no highlighter used**.  Is this your experience also?

**Comment by pyscripter** [comment]
Applied a similar fix.

**Comment by MShark67** [comment]
Yes. When I had the issue it was definitely without a highlighter being used.  Good catch!
