### ISSUE TITLE
Dragging the scrollbar thumb above the top or below the bottom of the scrollbar causes text to be selected and scrolled.

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#15]
The problem is in procedure TCustomSynEdit.MouseMove.  The second line is
  if (ssLeft in Shift) and MouseCapture then

changing it to:
  if (ssLeft in Shift) and MouseCapture and (not IsScrolling) then

solves the problem.

**Comment by pyscripter** [comment]
Thanks!
