### ISSUE TITLE
Update highlighters' Brackets and DefaultBrackets properties

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/SynEdit#35]
In the implementation of #31 TSynCustomHighlighter got a new published property Brackets, which is used in relation to this feature. It also has a protected DefaultBrackets property, which is used to in TSynCustomHighlighter.IsBracketsStored. Both are initialized to '{}[]{}'. The Brackets property is also used by TCustomSynEdit.GetMatchingBracket. 

A few of the existing highlighters need to be updated to adjust these properties appropriately.   (e.g. TSynHighlighterHTML should set brackets to '<>()[]')

**Comment by MShark67** [comment]
The two I know of that definitely need '<>' are TSynHighlighterHTML and TSynHighlighterXML.  That change does make things work for '<>' chars, however it only works for the other brace characters if their Attri is SymbolAttribute which is not the case for either.  I think that's maybe ok (perhaps we'll get other reports of that being an issue and can look into it then.)  Another one that might need '<>' is the object pascal one if it should handle the generics <t> syntax (although there would be a side effect with great than and less than symbols.)

**Comment by pyscripter** [comment]
The side effect you mention I think we need to avoid.  This was what convinced me set the default to '()[]{}'.

One possible change is to replace the check of SymbolAttributes with a check that it is not a comment or a string.   What do you think?

**Comment by MShark67** [comment]
That sounds promising, however, when I make that change here using the html highlighter, I start getting issues where the Token.Length is great than 1, which also causes that routine to return false.

**Comment by pyscripter** [comment]
Would something like this work?

```pascal
procedure TCustomSynEdit.HighlightBrackets;

  function PosHasBracket(Pos: TBufferCoord; const Line: string): Boolean;
  var
    Token: string;
    Attri: TSynHighlighterAttributes;
  begin
    Result := (Pos.Char <= Line.Length) and
     (fHighlighter.Brackets.IndexOf(Line[Pos.Char]) >= 0) and
     GetHighlighterAttriAtRowCol(Pos, Token, Attri) and
     (Attri <> fHighlighter.CommentAttribute) and
     (Attri <> fHighlighter.StringAttribute);
  end;

var
  BracketPos,
  MatchingBracketPos: TBufferCoord;
  HasBracket: Boolean;
  Indicator: TSynIndicator;
  Line: string;
begin
  if (eoBracketsHighlight in FOptions) and Assigned(fHighlighter) then
  begin
    Indicators.Clear(BracketsHighlight.MatchingBracketsIndicatorID);
    Indicators.Clear(BracketsHighlight.UnbalancedBracketIndicatorID);

    BracketPos := CaretXY;
    if BracketPos.Line > Lines.Count then Exit;
    Line := Lines[BracketPos.Line - 1];

    // First Look at the previous character like Site
    if BracketPos.Char > 1 then Dec(BracketPos.Char);
    HasBracket := PosHasBracket(BracketPos, Line);
    //if it is not a bracket then look at the next character;
    if not HasBracket and (CaretX > 1) then
    begin
      Inc(BracketPos.Char);
      HasBracket := PosHasBracket(BracketPos, Line);
    end;

    if HasBracket then
```

**Comment by pyscripter** [comment]
I think the above should allow matching the square brackets in CDATA  e.g.

```html
<style type="text/css">
/*<![CDATA[*/
body { background-image: url("marble.png?width=300&height=300") }     
/*]]>*/
</style>
```

or in XML

```xml
<DISPLAY_NAME Attribute="Y"><![CDATA[PFTEST0__COUNTER_6__:4:199:, PFTEST0__COUNTER_7__:4:199:]]></DISPLAY_NAME>
```

**Comment by MShark67** [comment]
Looks very good!

**Comment by pyscripter** [comment]
I have committed the above change.  Now we need to change the DefaultBrackets, Brackets properties of the highlighters for which the inherited values are not appropriate.

**Comment by MShark67** [comment]
Added those changes to HTML and XML highlighters.  Let me know if there are others.  I added {} to the HTML highlighter for inline css and scripts. #39

**Comment by pyscripter** [comment]
Merged.  Thanks Mark!  I cannot think of anything else.
