### ISSUE TITLE
Exception when setting options before parent control set.

### ISSUE THREAD

**Issue by vincentparrett** [pyscripter/SynEdit#44]
Not sure when this changed, but since switching to this fork I get an exception when setting the options when creating an editor in code.

````delphi
FEditor.Options := [eoDragDropEditing, eoEnhanceHomeKey, eoGroupUndo, eoScrollPastEol, eoShowScrollHint, eoTabIndent, eoTabsToSpaces, eoTrimTrailingSpaces]; 
             ^^^^^  boom!
....
FEditor.Parent := Self;
````
`exception class EInvalidOperation with message 'Control 'TSynEdit($FB3CA230)' has no parent window.`

The problem is the call to CalcTextAreaWidth in SetOptions - this function calls ClientWidth - which requires accesses the handle and... boom. 

One possible fix is to add this to CalTextAreaWidth

````delphi
procedure TCustomSynEdit.CalcTextAreaWidth;
begin
  if not HandleAllocated then
    exit;
...
````
That seems to work ok, since CalcTextAreaWidth gets called via WMSize events which happen after the parent is assigned. Happy to submit a PR for this if I am on the right track.

**Comment by pyscripter** [comment]
Thanks for reporting this.  
Implemented a different fix.  Please check.

**Comment by vincentparrett** [comment]
Looks good thanks.
