### ISSUE TITLE
Caret movement and positioning issue with non-breaking space (00A0) characters.

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#57]
I have a block of text that contains a number of 00A0 characters (which I think is a non-breaking space) and they mess up caret moving through the text as well as display.  Here's how to replicate the issue:

Steps:
  Type any normal character into the editor (say "a')
  Now type Alt-0160 using the number pad a number of times to enter non-breaking space characters.  Note that you won't see them or the caret move.
  Now type another normal character (say "b").
  You should see the caret move to the middle of the string, and moving the caret though the characters causes the caret to jump around a bit.

Let me know if you have any questions or need more info!  Thanks as always!

**Comment by MShark67** [comment]
I've added pull request #72 which I think may solve the issue (I've done limited testing.)
-Mark

**Comment by pyscripter** [comment]
Your PR has been merged.
