### ISSUE TITLE
Selecting multiple lines then hitting the TAB key should indent those lines instead of deleting them

### ISSUE THREAD

**Issue by jonjbar** [pyscripter/SynEdit#59]
### Steps to reproduce

- Select multiple lines
- Hit the `TAB` keyboard key or `SHIFT + TAB`

### Observation

The lines are deleted and replace by a tabulation.

### Expected

Those lines should be indented their indentation should be decreased based on the state of the `SHIFT` key.

**Comment by pyscripter** [comment]
Are you sure eoTabIndent is in options and the Tab key is linked to the ecTab command?

The above are the defaults.

**Comment by pyscripter** [comment]
Cannot reproduce with the default options of SynEdit.

**Comment by jonjbar** [comment]
I can confirm that "eoTabIndent" was not checked. When it is, it works as expected.
Sorry about that 😞
