### ISSUE TITLE
CharIndexToRowCol returns first pos of last line if Index > charcount.

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#62]
I noticed this when setting SelLength to a value more than the character count of the editor and noticing that it will select up the first character of the last line.  To fix it I just added the following check: 
```
    x := Length(Lines[y]);     <-- existing line
    if (y = Lines.Count - 1) and (Index >= Chars + x) then
      break;
```
Thanks!  -Mark

**Comment by pyscripter** [comment]
Used the slightly more efficient:

```pascal
    if Chars + x + 2 > Index then
    begin
      x := Index - Chars;
      Break;
    end
    else if (y = Lines.Count - 1) and (Index >= Chars + x) then
      Break;
```
Please confirm it works.
