### ISSUE TITLE
CopyToClipboard with dark background

### ISSUE THREAD

**Issue by groehner** [pyscripter/SynEdit#63]
When I copy source code to the clipboard from a SynEdit with a dark background and paste it into LibreOffice, the spaces appear black, which looks strange.
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/57d7400b-4e59-4dd2-8510-8fc966084efe)

After setting     HTMLExport.UseBackground := False; instead of True in 
procedure TSynEditDataObject.StreamHTML(Editor: TObject; Stream: TStream
I get a proper view:
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/27271551-2553-4b90-92d8-e714518b5baa)

**Comment by pyscripter** [comment]
@MShark67 Any ideas?

**Comment by JaFi-cz** [comment]
I have it done, I will send it to you tomorrow

Jan Fiala

Dne ne 28. 5. 2023 18:35 uživatel pyscripter ***@***.***>
napsal:

**Comment by JaFi-cz** [comment]
I won't send pull request, cause high activity in this unit.
Unit: SynExportHTML
Procedure procedure TSynExporterHTML.FormatBeforeFirstAttribute(BackgroundChanged,  (line about 313)

```
begin
  ...
  AddData('<div style="font-family: ' + FFont.Name + ', ''Courier New'', monospace; font-size: ' +
    FFont.Size.ToString + 'pt; white-space: pre; background-color: '+
    ColorToHTML(fBackgroundColor) + ';">');

```

**Comment by pyscripter** [comment]
@JaFi-cz Thanks!
@groehner Does this help?  If yes I will merge the change manually.

**Comment by groehner** [comment]
No, this doesn't help, for two reasons.
1. Now you get 
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/2737503d-4c1b-400b-a08f-b515c12e7c17)
The dark background ends at the end of a line, not a the end of the canvas and
if i copy source code for usage in a text document, the dark background is disturbing.
HTMLExport.UseBackground := False;  as suggested is a better solution.

2. The suggested solution is based on the `<div>` element, which gives an improper html output. I made a pull request for SynExportHTML with a proper `<pre>` element.

**Comment by JaFi-cz** [comment]
I got dark background to the line ends. I will check up differences between mine and published HTML exporter

**Comment by JaFi-cz** [comment]
I have same content as SynExporterHTML.pas from here
My formated text copy (I have eoCopyPlainText option as default)
```
  Synedit.Options := Synedit.Options - [eoCopyPlainText];
  Synedit.CopyToClipboard;
  Synedit.Options := Synedit.Options + [eoCopyPlainText];
end;

```

**Comment by pyscripter** [comment]
@groehner 

![image](https://github.com/pyscripter/SynEdit/assets/1311616/94651c14-bc17-432d-8ae6-25d9140aeb2e)

I copied and pasted into PowerPoint.  The top is with your PR and the bottom with the current master.

Your version misses the line breaks which are important with code. 

Would setting UseBackground to False or making it an option resolve this issue?

**Comment by JaFi-cz** [comment]
@pyscripter 
can you set dark background and CopyToClipboard with my modification? Does it make whole background dark for you or not?

**Comment by JaFi-cz** [comment]
And one another comment. Synedit font and background color must be set too, not only highlighter attributes!

**Comment by pyscripter** [comment]
> Does it make whole background dark for you or not?

It does in Word.  Powerpoint seems to ignore the background color.

![image](https://github.com/pyscripter/SynEdit/assets/1311616/a568be81-ee12-4cde-9dce-ee6282e67fb1)

> Synedit font and background color must be set too, not only highlighter attributes!

Are you sure?  Why is that?

```
    if Assigned(fHighlighter) and Assigned(fHighlighter.WhitespaceAttribute) and fUseBackground then
      fBackgroundColor := fHighlighter.WhitespaceAttribute.Background;
```

By the way your change should only be applied if UseBackground is True.

```pascal
procedure TSynExporterHTML.FormatBeforeFirstAttribute(BackgroundChanged,
  ForegroundChanged: boolean; FontStylesChanged: TFontStyles);
var
  StyleName: string;
  StyleValue: string;
  BkgColor: string;
begin
  // Cache all our CSS values.
  EnumHighlighterAttris(Highlighter, True, AttriToInlineCSSCallback, []);
  if UseBackground then
    BkgColor := ' background-color: '+ ColorToHTML(fBackgroundColor) + ';'
  else
    BkgColor := '';
  AddData('<div style="font-family: ' + FFont.Name + ', ''Courier New'', monospace; font-size: ' +
    FFont.Size.ToString + 'pt; white-space: pre;' + BkgColor + '">');
```

**Comment by groehner** [comment]
I was irritated about the missing line breaks. But now I see that you are using not the version i tried to make a pull request from.

In your procedure FormatBeforeFirstAttribute a `<div>` element is used:

```python
AddData('<div style="font-family: ' + FFont.Name + ', ''Courier New'', monospace; font-size: ' +
    FFont.Size.ToString + 'pt; white-space: pre;' + BkgColor + '">');
``` 

My suggested solution is using a `<pre>` element.
```python
procedure TSynExporterHTML.FormatBeforeFirstAttribute(BackgroundChanged,
  ForegroundChanged: boolean; FontStylesChanged: TFontStyles);
var
  StyleName: string;
  StyleValue: string;
begin
  // Cache all our CSS values.
  EnumHighlighterAttris(Highlighter, True, AttriToInlineCSSCallback, []);
  AddData('<pre style="font-family: ' + FFont.Name + ', ''Courier New'', monospace; font-size: ' +
    FFont.Size.ToString + 'pt;">' + sLineBreak);
  if FCreateHTMLFragment or FInlineCSS then
  begin
    FStyleValueCache.TryGetValue(Highlighter.GetTokenAttribute, StyleValue);
    if StyleValue <> '' then
      AddData('<span style="' + StyleValue + '">')
    else
      AddData('<span>');
  end
  else
  begin
    StyleName := GetStyleName(Highlighter, Highlighter.GetTokenAttribute);
    AddData('<span class="' + StyleName + '">');
  end;
end;
``` 
I now attached a zipped Version of SynExportHTML 


[SynExportHTML.zip](https://github.com/pyscripter/SynEdit/files/11592717/SynExportHTML.zip)

**Comment by pyscripter** [comment]
> I was irritated about the missing line breaks. But now I see that you are using not the version i tried to make a pull request from.

I did use your PR version in my testing, but I will try again.

I tried again with the zipped file and I get the same result in Powerpoint:

![image](https://github.com/pyscripter/SynEdit/assets/1311616/b2830e4c-e10d-46e7-9a62-8e39f1fed6c9)

and in Word (compare to the image a couple of posts up):

![image](https://github.com/pyscripter/SynEdit/assets/1311616/3d832b20-eb44-418a-9237-2cd94f404e82)

Also your version will never paint a dark background, which is what I prefer, even though UseBackground = True.


I am not an HTML expert but I believe what you say that the "pre" tag is preferable to "div".   But there are two issues with your PR:
-  UseBackground does not work
- Line breaks are not preserved

If you can fix those then I will accept your PR.

Alternatively, if the current version works for you with UseBackground = False,  I can add a SynEdit option eoNoHTMLBackground to control the behavior when copying.   Would that be OK?

**Comment by pyscripter** [comment]
### `<pre> vs <div>`
From ChatGPT:

In HTML, the `<pre>` tag defines preformatted text. The text inside a `<pre>` element is displayed in a fixed-width font (usually Courier), and it preserves both spaces and line breaks. The `<div>` tag is used as a container for HTML elements - **which is then styled with CSS** or manipulated with JavaScript. The `<div>` tag is easily styled by using the class or id attribute. [The `<div>` tag is also used to group block-elements to format them with CSS](https://stackoverflow.com/questions/2226562/what-is-the-difference-between-p-and-div)[1](https://stackoverflow.com/questions/2226562/what-is-the-difference-between-p-and-div)[2](https://www.w3schools.com/Tags/tag_div.asp).

The main difference between the two tags is that `<pre>` preserves whitespace and line breaks while `<div>` does not. [Another difference is that `<pre>` is used for preformatted text while `<div>` is used as a container for other HTML elements](https://stackoverflow.com/questions/2226562/what-is-the-difference-between-p-and-div)[1](https://stackoverflow.com/questions/2226562/what-is-the-difference-between-p-and-div)[2](https://www.w3schools.com/Tags/tag_div.asp).

With the following:

```css
div
{
  font-family: "Courier New", monospace;
  white-space: pre;
}
```
div behaves like a pre.  

I think there is nothing wrong with using div. Either should work.

**Comment by pyscripter** [comment]
@groehner Could you please try the updated version with  eoNoHTMLBackground set?  Does it work as you expect?

**Comment by groehner** [comment]
During my experiments I saw that the clipboard HTML format is not very well supported by applications.
With Word in the desktop version you get a dark background, when Synedit hasn't the option  eoNoHTMLBackground.
In Office 365 Word and in LibreOffice writer yout get a bright background.

So in Word as desktop version eoNoHTMLBackground works for the background.
You can close CopyToClipbaord with dark background.
But there are still  errors in ExportHTML

**Comment by pyscripter** [comment]
@groehner 
Thanks!
I am looking at ExportHTML right now.
