### ISSUE TITLE
Highlighting blocks by drawing lines for block pairs in code, not in Gutter.

### ISSUE THREAD

**Issue by Vizit0r** [pyscripter/SynEdit#68]

**Comment by Vizit0r** [comment]
sorry, mesage sent too fast, was not completed.

So, in Delphi and in some other editors it looks like this:
![image](https://github.com/pyscripter/SynEdit/assets/2213917/bb1b5027-4c02-4c2c-9798-1ceac26b585c)

As you can see, it drawing standart pairs, according to selected highligher. For example above thats Pascal (DWS) with pairs [begin|record|class|case|try...end], for other langs accordingly.

At the moment using Indicators i can make changes for 1 line only, not for couple of them, so i can highlight only words for beginning and end of blocks (and paint line to divide methods visually). 
![image](https://github.com/pyscripter/SynEdit/assets/2213917/6dd82d92-7c1d-4ea1-8d2d-3071e8f3c170)


Thats good ofc... but not enough :)

So, we need some extensions like MultiLine Indicators or something (plus extend TSynFoldRange to contain info about X position of block beginner and closer to draw lines correctly),.

BTW, on the picture above this lines on Gutter have no sense at all, really, and looks very strange. 

And also thanks for your work!

**Comment by Vizit0r** [comment]
[SynEditCodeFolding.zip](https://github.com/pyscripter/SynEdit/files/11622824/SynEditCodeFolding.zip)



Modified SynEditCodeFolding.pas  with CharPos for Range "From" and "To" Lines.
Also SynHighlighterDWS, modified for bug removing when range parsing dying on lines like "end else begin" and with CharPos  for Fold lines support (+ little bit extended key words to 
```
  RE_BlockBegin.Create('\b(begin|record|class|case|try)\b', [roNotEmpty, roIgnoreCase]);
  RE_BlockEnd.Create('\bend\b', [roNotEmpty, roIgnoreCase]);
  RE_Code.Create('^\s*(function|procedure|constructor|destructor)\b', [roNotEmpty, roIgnoreCase]);
```


I'm using it for highlight words as on my last screenshot.

**Comment by JaFi-cz** [comment]
Why don't you switch on guides?

![2023-06-01 10_21_00-Novy1 pas -  Novy1 pas _](https://github.com/pyscripter/SynEdit/assets/83579818/c4c6e15f-dd44-46ea-b7c1-d4bad568445d)

**Comment by Vizit0r** [comment]
@JaFi-cz 
because painting of indent lines, and highliting ranges - that totally different story.

Just compare my first screenshot and yours - and try to find amount of critical differences...

**Comment by Vizit0r** [comment]
few thing to demonstrate how indents can be painted depends frob tab width.
![image](https://github.com/pyscripter/SynEdit/assets/2213917/c8efa6cb-4f47-4f58-bf13-863ae0e1b6ba)
or
![image](https://github.com/pyscripter/SynEdit/assets/2213917/b83773e3-dfb6-4270-bdc5-23d44448e90c)

So, i dont want to explain to user, what is a correlation between TabWidth in settings with drawing lines, for him thats will sounds crazy.

Blocks(Ranges) are blocks, indents are indents.

**Comment by Vizit0r** [comment]
[SynEditCodeFolding.zip](https://github.com/pyscripter/SynEdit/files/11648244/SynEditCodeFolding.zip)
small tuning and adjustments for ranges FromCharPos and ToCharPos
+ same for SynHighlighterDWS.pas - adjustment for Regions, etc.

**Comment by pyscripter** [comment]
Fixed in the multicaret branch.  See #104.
