### ISSUE TITLE
Background color is not correctly exported to RTF

### ISSUE THREAD

**Issue by jonjbar** [pyscripter/SynEdit#73]
Consider the attached project, using Delphi 11.3 and the latest commit of SynEdit, as of now:

- It highlights XML where some items have a background color
- The RTF exporter has the "UseBackgroundColor" set to True
- The generated output.rtf has a messed up background, starting at the item with a background color

[syn-rtf-bg.zip](https://github.com/pyscripter/SynEdit/files/12130002/syn-rtf-bg.zip)

**Comment by pyscripter** [comment]
I am not using RTF and I have not ever touched this code.   It would be nice if you find a fix and provide a PR.

**Comment by pyscripter** [comment]
@m-matsubara  Is this something you can help with?

**Comment by jonjbar** [comment]
This seems to fix the problem. What do you think ?
[Changes-On-f1a128.patch](https://github.com/user-attachments/files/16458114/Changes-On-f1a128.patch)

**Comment by pyscripter** [comment]
@jonjbar  If you have tested and it works I can commit this.   I don't know much about the rtf format to judge.  Please let me know.

I also noticed that you have suggested the original line in https://github.com/TurboPack/SynEdit/issues/63.

**Comment by pyscripter** [comment]
Your patch has been applied.
