### ISSUE TITLE
Unbalanced stack error with small MaxUndo value greater than zero.

### ISSUE THREAD

**Issue by MShark67** [pyscripter/SynEdit#80]
Usage case:  I was trying to have a SynEdit work like a normal Memo (as far as Undo at least) in order to reduce memory usage.  In this case I tried setting MaxUndo to 1.  With MaxUndo at 1 I see the error right away.  Here are the steps to replicate it:

To replicate the error:
  Drop a TSynEdit on a form.
  Change MaxUndo to 1.
  Run the app.
  Type two characters and then the enter key.
  You should see an exception with:  
     Project Project1.exe raised exception class EListError with message 'Unbalanced stack or queue operation'. 

Note that this is just the easiest way to see an error.

In looking into the code, I see that I misunderstood the MaxUndo setting and really it should be set at a higher number and is just used to restrict total memory use.   I don't think my original intention to mimic one level of undo is possible at least with that setting (which is fine btw, it's a minor issue.)  Setting MaxUndo to a larger number (tested with 10) seems to solve the error message.

-Mark

**Comment by pyscripter** [comment]
The exception has been fixed.

MaxUndo determines the length of the Undo/Redo lists.   As you say,  it can be set to restrict the memory used by Undo/Redo. 

Editing actions can create multiple undo items.   So you cannot replicate the TMemo behavior of undoing/redoing only one action.
