### ISSUE TITLE
SynEdit changes modified state to true with eoTrimTrailingSpaces option enabled

### ISSUE THREAD

**Issue by dados** [pyscripter/SynEdit#85]
Hi,

The eoTrimTrailingSpaces option triggers the modified property to change to true just by moving around with arrow keys.

So if you load a file into SynEdit (clear undo and set modified to false) and the file contains trailing spaces the modified property will change to true just by moving around with arrow keys.

Is this was intended behaviour ?

**Comment by pyscripter** [comment]
Yes it is.   Trailing spaces are removed, so the the text buffer is changed.

**Comment by dados** [comment]
Okey I understand.
Just wanted to check if this was intended functionality as the user is not directly modifying the content but just moving the cursor around with the arrow keys or mouse with this result.
Thanks
