### ISSUE TITLE
SynEditOptionsDialog.dfm - the form's height is not enough

### ISSUE THREAD

**Issue by dados** [pyscripter/SynEdit#86]
Hi, 

If you open the SynEditOptionsDialog unit and look at the form you will see that the forms height is not enough for the OK and Cancel button to be visible.

**Comment by dados** [comment]
Here is my modification of the form.
I noticed that some labels like in the Options tab where not long enough and other where a bit tight.
So I made some additional alignment changes within the form. 
Please use it if it suites you

[SynEditOptionsDialog.zip](https://github.com/pyscripter/SynEdit/files/15476796/SynEditOptionsDialog.zip)

**Comment by pyscripter** [comment]
I have committed your changes (minus Explicit and DesignSize properties).
