### ISSUE TITLE
Show control characters.

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/SynEdit#87]
If the text contains not printable control characters those Syn Edit does not display them.

VS Code has an option "Render Control Characters"  With that option on it looks like this:
![image](https://github.com/pyscripter/SynEdit/assets/1311616/0e65d8d0-c21e-4a31-9e4d-9015efdde17c)

SynEdit could introduce a similar option, or at least display them when eoShowSpecialChars is set.   The [Unicode Control Pictures](https://en.wikipedia.org/wiki/Unicode_control_characters) set could be used to display such characters.

This is how it would look:
![image](https://github.com/pyscripter/SynEdit/assets/1311616/a0d89deb-cf68-4416-a5b5-908dea863903)

**Comment by pyscripter** [comment]
Control chars are now rendered when eoShowSpecialChars is on.
I left a RenderControlChars option to always show control chars for later.

**Comment by DGH2112** [comment]
Thanks @pyscripter, this is exactly what I was thinking (sorry, not in a position to run any code until later in the week).
