### ISSUE TITLE
Finer control of special chars shown.

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/SynEdit#89]
Currently when eoShowSpecialChars is in Options,  SynEdit shows whitespace (space + Tabs), control characters and EOL symbols.   I personally do not find the EOL symbols useful.   The proposal is to have finer control over what is drawn.  This involves,

1.  Dropping the option eoShowSpecialChars 
2.  Introducing a new property VisibleSpecialChars

```pascal
type
  TSynSpecialChars = (scWhitespace, scControlChars, scEOL);
  TSynVisibleSpecialChars = set of TSynSpecialChars;

  property VisibleSpecialChars: TSynVisibleSpecialChars
```  

***This is a breaking change***

**Comment by DGH2112** [comment]
I'm okay with this change.

**Comment by m-matsubara** [comment]
I thought it was wonderful.
But the colors don't seem to be correct in comments or string literals.

![image](https://github.com/pyscripter/SynEdit/assets/12123551/f4e9acf7-9f8d-4097-a8e3-ed0082695dfb)

**Comment by m-matsubara** [comment]
It seems like the caret is out of place...
(Font is Consolas)

![image](https://github.com/pyscripter/SynEdit/assets/12123551/38d7b2c5-267b-4072-a6e7-71e49ab889ac)

**Comment by pyscripter** [comment]
It is up to the highlighter to determine the color.   Within code they might be painted with an Error Attribute to indicate a syntax error.   In strings and comments they are part of them and should be painted accordingly.  Most highlighters consider control characters as whitespace.

**Comment by pyscripter** [comment]
> It seems like the caret is out of place...

I will look into it.

**Comment by m-matsubara** [comment]
> It is up to the highlighter to determine the color. Within code they might be painted with an Error Attribute to indicate a syntax error. In strings and comments they are part of them and should be painted accordingly. Most highlighters consider control characters as whitespace.

got it. To be honest, I think it would be better if control characters were displayed in different colors, but I respect that idea.

**Comment by pyscripter** [comment]
I have fixed the cursor positioning error in https://github.com/pyscripter/SynEdit/commit/2760affb659b143b9511fed47921a4c1d783847c.  **Could you please test it**.

There is still a slight issue when the font style is [fsBold, fsItalic] and you have many graphical unicode characters (control chars, emojis) on the same line.   But this is highly uncommon.   I will leave that for another day.
