### ISSUE TITLE
Character constants should not depend on user locale (codepage)

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/SynEdit#95]
I would suggest the following.    

- All character literals greater than 127 will be coded as #$xxxx. 
- The unnecessary WideChar typecast as in `WideChar(#$00B4)` will be removed.
- This PR will be closed and will be replaced by a more comprehensive one covering all SynEdit units.

@m-matsubara @MShark67 Any volunteers for doing this?

_Originally posted by @pyscripter in https://github.com/pyscripter/SynEdit/issues/93#issuecomment-2155084625_

**Comment by m-matsubara** [comment]
Create a pull request.

**Comment by pyscripter** [comment]
> Create a pull request.

Do you mean you will submit a PR?  Thanks! Can't see one yet.
